volumes:
  data:
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - data:/var/lib/mysql
